//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.RolePermission.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RolePermissionEntities : DbContext
    {
        public RolePermissionEntities()
            : base("name=RolePermissionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SMEXCEPTIONTB> SMEXCEPTIONTB { get; set; }
        public virtual DbSet<SMFIELD> SMFIELD { get; set; }
        public virtual DbSet<SMFUNCTB> SMFUNCTB { get; set; }
        public virtual DbSet<SMLOG> SMLOG { get; set; }
        public virtual DbSet<SMMENUROLEFUNCTB> SMMENUROLEFUNCTB { get; set; }
        public virtual DbSet<SMMENUTB> SMMENUTB { get; set; }
        public virtual DbSet<SMROLETB> SMROLETB { get; set; }
        public virtual DbSet<SMUSERTB> SMUSERTB { get; set; }
    }
}
