//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.RolePermission.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMEXCEPTIONTB
    {
        public string ID { get; set; }
        public string EXCEPTIONTYPE { get; set; }
        public string MESSAGE { get; set; }
        public string RESULT { get; set; }
        public string REMARK { get; set; }
        public string STATE { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
    }
}
