//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.RolePermission.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMFUNCTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SMFUNCTB()
        {
            this.SMMENUROLEFUNCTB = new HashSet<SMMENUROLEFUNCTB>();
            this.SMMENUTB = new HashSet<SMMENUTB>();
        }
    
        public int FUNC_ID { get; set; }
        public string FUNC_CODE { get; set; }
        public string FUNC_NAME { get; set; }
        public string EVENT_NAME { get; set; }
        public string STATUS { get; set; }
        public string PARENTFUNC_CODE { get; set; }
        public string CLASS_NAME { get; set; }
        public Nullable<int> ORDERCODE { get; set; }
        public string SM_SYSTEM { get; set; }
        public Nullable<int> IMGINDEX { get; set; }
        public string ICONIC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMMENUROLEFUNCTB> SMMENUROLEFUNCTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMMENUTB> SMMENUTB { get; set; }
    }
}
