//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.RolePermission.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMMENUTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SMMENUTB()
        {
            this.SMMENUROLEFUNCTB = new HashSet<SMMENUROLEFUNCTB>();
            this.SMMENUTB1 = new HashSet<SMMENUTB>();
            this.SMFUNCTB = new HashSet<SMFUNCTB>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> PARENTID { get; set; }
        public string URL { get; set; }
        public string ICONIC { get; set; }
        public Nullable<int> SORT { get; set; }
        public string REMARK { get; set; }
        public string STATE { get; set; }
        public string CREATEPERSON { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public string UPDATEPERSON { get; set; }
        public string ISLEAF { get; set; }
        public Nullable<int> MENULEVEL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMMENUROLEFUNCTB> SMMENUROLEFUNCTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMMENUTB> SMMENUTB1 { get; set; }
        public virtual SMMENUTB SMMENUTB2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMFUNCTB> SMFUNCTB { get; set; }
    }
}
