//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.RolePermission.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMROLETB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SMROLETB()
        {
            this.SMMENUROLEFUNCTB = new HashSet<SMMENUROLEFUNCTB>();
            this.SMUSERTB = new HashSet<SMUSERTB>();
        }
    
        public int ROLE_ID { get; set; }
        public string ROLE_NAME { get; set; }
        public Nullable<System.DateTime> CREATION_TIME { get; set; }
        public Nullable<int> CREATION_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_TIME { get; set; }
        public Nullable<int> UPDATE_USER { get; set; }
        public string REMARK { get; set; }
        public string STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMMENUROLEFUNCTB> SMMENUROLEFUNCTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMUSERTB> SMUSERTB { get; set; }
    }
}
