//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.RolePermission.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMUSERTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SMUSERTB()
        {
            this.SMROLETB = new HashSet<SMROLETB>();
        }
    
        public int USER_ID { get; set; }
        public string U_ID { get; set; }
        public string U_PASSWORD { get; set; }
        public string GENDER { get; set; }
        public string USER_NAME { get; set; }
        public Nullable<System.DateTime> CREATION_TIME { get; set; }
        public Nullable<int> CREATION_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_TIME { get; set; }
        public Nullable<int> UPDATE_USER { get; set; }
        public string STATUS { get; set; }
        public Nullable<int> TYPE_ID { get; set; }
        public Nullable<int> COMPONENT_ID { get; set; }
        public Nullable<int> COMMUN_ID { get; set; }
        public string GUILD_CODE { get; set; }
        public Nullable<int> UNPAYAMT { get; set; }
        public string CONIFGUSEFUL { get; set; }
        public Nullable<int> FLAG { get; set; }
        public string ID_NO { get; set; }
        public Nullable<int> ISAUDIT { get; set; }
        public string AUDITPASSWORD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMROLETB> SMROLETB { get; set; }
    }
}
